create hello page
khasang-incubator/rTrail pull request #23
Opened 2018-06-12 21:12 UTC by dvSokolov

2018-06-17 16:54 UTC, SKuznet requested changes

2018-06-17 16:54 UTC, SKuznet commented on src/main/java/io/khasang/rtrail/controller/HelloPageController.java
> +//        TODO Generate page attributes by URL
why commented code here?

2018-06-17 19:18 UTC, dvSokolov commented
Deleted comments

2018-06-19 16:38 UTC, SKuznet approved these changes

2018-06-19 16:56 UTC, merged